	<div id="opening">	
		<h2>Disclaimer</h2>
		<p>
			The calculation of the Retirement Planner is based on certain assumptions including the
			hypothetical data input by the user. It does not take into account individual needs or circumstances.
			The results generated by this Retirement Planner may differ from other similar calculators in the
			market when different assumptions are adopted. Please note that the results do not represent, or
			promise, the actual amount of the retirement benefits the user will receive at retirement; and that they
			are for reference only and are not intended as and cannot be a substitute for professional financial
			advice. The shall not be liable for any human or mechanical errors or omissions in or any reliance
			placed upon the results; nor shall it be liable for the consequences of any decision or action taken
			upon or as a result of the information provided by the Retirement Planner.
		</p>
		<div class="confirmBtn">
			<a href="javascript:$.fancybox.close();" class="planBtn">Continue</a>
		</div>	
	</div>
	
	<div id="mpf_Rules01" style="display:none;">	
		<p>
			According to the Mandatory Provident Fund Schemes Ordinance, withdrawal of MPF accrued benefits is only allowed when MPF scheme members reach the age of 65.
		</p>
		<div class="confirmBtn">
			<a href="javascript:$.fancybox.close();" class="planBtn">Continue</a>
		</div>	
	</div>
	
	<div id="retire_require" style="display:none;">
		<p>
			The "expected amount required when you retire" is a negative figure because 
			your expected income after retirement (including civil servant’s monthly pension, if any) 
			is higher than your expected retirement expenses.
		</p>
		<div class="confirmBtn">
			<a href="javascript:$.fancybox.close();" class="planBtn">Continue</a>
		</div>	
	</div>
	
	<!--<div id="loadLay" class="hide" style="display:none;">
		<div class = "loadingMa"></div>
		<div id="loadLayerCon">
			<img src="../../images/share/loading.gif" alt="loading.." style="height:20px; width:20px;" />
			<span>內容正在加載, 請稍等...</span>
		</div>
	</div>-->
	
	<div id="useExplain">
		<h1 class="u_guide_title">About Retirement Planner</h1>
		<p>
			The Retirement Planner includes five sections, namely "About you",
			"How much do you need for retirement", "Your retirement schemes", "Your
			savings and investments" and "Other retirement income".
		</p>
		<p>
			After completing relevant information in the above sections, you will be
			provided an analysis report and action plan which you could use to improve
			your retirement plan. 
		</p>
		<ul>
			<li>Please input the relevant information on each page and press the "next" button to continue. You can also click on the "previous" button to go back and edit the inputs of previous pages.</li>
			<li>After completing all five sections, please press the "result" button to view your analysis report and action plan.</li>
			<li>
				You can press <img src="../../images/share/pdf.png" alt="PDF Button" class="btnExplain" /> to view and save your report in PDF format,
				or press <img src="../../images/share/print.png" alt="print Button" class="btnExplain" /> to print the full report.
			</li>
			<li>The personal data you have provided will only be analysed once, the Investor Education Centre (IEC) will not store your data and report.</li>
			<li>
				The information you have provided for this retirement planner is your
				personal information and can be sensitive. While this retirement planner
				allows you to save your data and view the information in different formats,
				please note the following measures for your consideration to protect your
				information/records against unauthorised or accidental access,
				processing or erasure:
				<ul class="secondUL">
					<li>Avoid using publically shared computers, such as those found in libraries or cyber cafes;</li>
					<li>Save your downloaded files to a secure location to avoid access by third parties;</li>
					<li>Do not leave your computer unattended while using this retirement planner;</li>
					<li>Always remember to log off properly or close all browser windows immediately after use;</li>
					<li>Install reputable anti-virus or security protection software on your computer.</li>
				</ul>
			</li>
		</ul>
		<h1 class="p_sub_title">Assumptions and methodology</h1>
		<p style="text-decoration:underline;">Default values</p>
		<p>The following fields have been set with default values, which can be changed by the user:</p>
		<ul>
			<li>Expected inflation rate (p.a.);</li>
			<li>Expected rate of return during retirement;</li>
			<li>Expected annual salary growth;</li>
			<li>Expected annual MPF investment return rate;</li>
			<li>Expected rate of return (p.a.) for savings and investments.</li>
		</ul>
		
		<p style="text-decoration:underline;">MPF benefit projections</p>
		<ul>
			<li>
				The amount of MPF mandatory contributions made are subject to the
				existing statutory minimum and maximum levels of income which are
				HKD7,100 and HKD30,000 per month respectively. Both levels are
				adjusted automatically every four years according to the rate of inflation as
				measured by the annualised Composite Consumer Price Index change
				over the past 10 years.
			</li>
			<li>An annual bonus, if any, is included in the relevant income of the last month of each year.</li>
			<li>
				Voluntary contributions (if any) are made as a percentage of the relevant
				income per month. There is no upper limit to the level of voluntary
				contributions, and all such contributions are fully vested.
			</li>
			<li>Special voluntary contributions (if any) are made in a fixed dollar amount.</li>
			<li>
				Mandatory contributions, voluntary contributions and special voluntary
				contributions are made on a monthly basis and will continue to be made
				until the retirement age.
			</li>
			<li>Existing MPF balance, as input by the user, is assumed to be fully vested.</li>
			<li>
				There is no long service payment/severance payment offsetting, no default
				contribution, no breaking of employment, and no early withdrawal during
				the period of projection.
			</li>
		</ul>
		
		<p style="text-decoration:underline;">Benefits of other retirement schemes</p>
		<ul>
			<li>
				There are different methodologies to calculate/determine the benefits of
				other retirement schemes (eg ORSO, Civil Service Pension,
				Grant/Subsidized Schools Provident Fund etc). As such, this retirement
				planner will not calculate these retirement benefits. Users can check with
				the service providers or employers for assistance in calculating the
				expected retirement benefits, and then input the figures accordingly.
			</li>
		</ul>
		
		<p style="text-decoration:underline;">Your savings and investments</p>
		<ul>
			<li>Monthly retirement saving plans (if any) will continue to be made until the retirement age.</li>
		</ul>
		
		<p style="text-decoration:underline;">Result</p>
		<ul>
			<li>
				"The expected reserve accumulated when you retire" is the sum of
				expected MPF accrued benefits/ORSO retirement benefits/Civil Service
				Pension lump sum gratuity/Grant/Subsidized Schools Provident Fund
				benefits, plus expected savings and investments at retirement age.
			</li>
			<li>
				"The expected amount required when you retire" equals to the expected
				total retirement expenses minus the total discounted monthly pension and
				other retirement income. If the expected total retirement expenses are smaller than the sum of total discounted monthly pension and other retirement income, 
				the "expected amount required when you retire" will become a negative figure. 
				Please note that expected total retirement expenses do not include
				inheritance and funeral cost.
			</li>
			<li>
				The presentation of the expected shortfall at retirement age and the
				current annual income is for illustration purpose only. The value of the
				annual income does not take into account the effect of income growth.
			</li>
		</ul>
		<div class="confirmBtn">
			<a href="javascript:$.fancybox.close();" class="planBtn">Continue</a>
		</div>	
	</div>
	
<!--Mail Share-->
	<div id="eMailShare" class="tips">	
		<h2 class="eMail_Title">Retirement Planner</h2>
		<p class="eMail_Content">
			How much do you need for retirement? Use the Retirement Planner to work out your retirement budget and take home our free analysis report and action plan now!
		</p>
	</div>
	
<!--FeedBack-->
	<div id="user_feedBack" class="tips">	
		<h2 class="feedback_to">info@thechinfamily.hk</h2>
		<p class="feedback_subject">Feedback on Retirement Planner</p>
	</div>
	

<!--Slide 1-->
	<div id="tips01" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected retirement age</h2>-->
		<p class="tips_Content">
			Retirement age varies across different people. It tells you how many years you have left to accumulate
			savings. The earlier you retire, the more money you need to cope with expenses.
		</p>
	</div>
	
	<div id="tips02" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Life expectancy</h2>-->
		<p class="tips_Content">In 2013, the expectancy of life at birth for men and women was 81 years and 87 years respectively.</p>
	</div>
	
<!--Slide 2-->
	<div id="tips03" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected inflation rate</h2>-->
		<p class="tips_Content">
			The annualised percentage change of the Composite Consumer Price Index over the past 5 years
			(2010-2014) and 10 years (2005-2014) was 4.1% and 3.0% respectively.
		</p>
	</div>
	
	<div id="tips04" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected rate of return during retirement eg interests or returns from other investments</h2>-->
		<p class="tips_Content">
			The annualised return rate of Tracker Fund of the past 10 years was 5.2% (as at December 2014). Please
			note that past performance is not a reliable guide for future performance.
		</p>
	</div>
	
<!--Slide 3-->
	<div id="tips05" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">An employee</h2>-->
		<p class="tips_Content">
			If you are an employee, both you and your employer are required to contribute 5% of your relevant income
			respectively as MPF mandatory contributions, subject to the minimum and maximum relevant income levels.
		</p>
	</div>
	
	<div id="tips06" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">A self-employed person</h2>-->
		<p class="tips_Content">
			If you are a self-employed person, you are required to contribute 5% of your relevant income as MPF
			mandatory contributions, subject to the minimum and maximum relevant income levels. A self-employed
			person is a person who earns income from the production of, or trade in goods or services in a capacity other
			than an employee.
		</p>
	</div>
	
	<div id="tips07" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Relevant income</h2>-->
		<p class="tips_Content">
			For employees, relevant income refers to any wage, salary, leave pay, fee, commission, bonus, gratuity,
			perquisite or allowance expressed in monetary terms, paid or payable by an employer to an employee. For
			self-employed persons, there are a few ways to ascertain the relevant income, please refer to the webpage re
			contributions of the MPFA website for details.
		</p>
	</div>
	
	<div id="tips08" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Monthly salary</h2>-->
		<p class="tips_Content"></p>
	</div>
	
	<div id="tips09" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Annual bonus (if any)</h2>-->
		<p class="tips_Content"></p>
	</div>
	
	<div id="tips10" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected annual salary growth</h2>-->
		<p class="tips_Content">The annualised percentage change of Nominal Indices of Payroll Per Person Engaged from Q4 2004 to Q4 2013 was 3.9%.</p>
	</div>
	
	<div id="tips11" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Monthly voluntary contribution</h2>-->
		<p class="tips_Content"></p>
	</div>
	
	<div id="tips12" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Employee’s voluntary monthly contribution</h2>-->
		<p class="tips_Content"></p>
	</div>
	
	<div id="tips13" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Employer’s voluntary monthly contribution</h2>-->
		<p class="tips_Content">Any additional contribution paid by the employer on top of the 5% mandatory contribution is considered to be voluntary contribution.</p>
	</div>
	
	<div id="tips14" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Monthly special contribution</h2>-->
		<p class="tips_Content">
			This is a fixed amount contribution made to your MPF account in addition to mandatory contribution and
			voluntary contribution. Special voluntary contribution is paid directly by a relevant employee to the
			trustee without going through the employer. Making special voluntary contribution and withdrawal of its
			accrued benefits are neither tied to employment nor subject to preservation requirements.
		</p>
	</div>
	
	<div id="tips15" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Your existing MPF balance</h2>-->
		<p class="tips_Content">You can check your annual benefit statements, make sure to include all your MPF accounts.</p>
	</div>
	
	<div id="tips16" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected annual MPF investment return rate</h2>-->
		<p class="tips_Content">The annualised internal rate of return since inception of the MPF system in year 2000 to 31 December 2014 was 4.0%. Please note that past performance is not a reliable guide for future performance.</p>
	</div>
	
<!--Slide 4-->
	<div id="tips17" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Current balance of all savings and investments</h2>-->
		<p class="tips_Content">Please include all non-retirement scheme savings and investments that were made for retirement purpose.</p>
	</div>
	
	<div id="tips18" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Monthly savings and investments</h2>-->
		<p class="tips_Content">For example, monthly investment plan for equities, funds etc.</p>
	</div>
	
	<div id="tips19" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected rate of return</h2>-->
		<p class="tips_Content">The annualised return rate of Tracker Fund of the past ten years was at 5.2% (as at December 2014). Please note that past performance is not a reliable guide for future performance.</p>
	</div>
	
<!--Slide 5-->
	<div id="tips20" class="tips">	
		<span class="tips_arrow"></span>
		<!--<h2 class="tips_Title">Expected annual growth rate of these incomes during retirement</h2>-->
		<p class="tips_Content">
			The annualised percentage change of the Composite Consumer Price Index over the past 5 years
			(2009-2013) and 10 years (2004-2013) was 3.3% and 2.5% respectively. The annualised percentage change
			of Nominal Indices of Payroll for Person Engaged from Q4 2004 to Q4 2013 was 3.9%.
		</p>
	</div>

<!--Slide 6-->
	<div id="winAlert00" style="display:none;">重設將會清空所有輸入的值，確定要重設嗎？</div>