		<div id="opening">
				
					<h2>Disclaimer</h2>
					<p>
						The following financial health check is based on certain assumptions including hypothetical data input by the user. 
						The results generated by our financial health check tool are for reference only and are not intended as and cannot be a substitute for professional 
						financial advice. The IEC shall not be liable for any human or mechanical errors or omissions in or any reliance placed upon the results; 
						nor shall it be liable for the consequences of any decision or action taken upon or as a result of the information provided by the financial health 
						check.
					</p>
					<div class="confirmBtn">
						<a href="javascript:$.fancybox.close();" class="planBtn">Continue</a>
					</div>	
		</div>