var sys_globalVar = new Array();
sys_globalVar["sys_topLogo_en"] = "<div id='sys_topLogoDiv' style='display:inline;'><a href='/web/en/index.html' class='logo-iec'><img src='/web/images/common/img-logo-iec.jpg' alt='' /></a></div>";
sys_globalVar["sys_topLogo_tc"] = "<div id='sys_topLogoDiv' style='display:inline;'><a href='/web/tc/index.html' class='logo-iec'><img src='/web/images/common/img-logo-iec.jpg' alt='' /></a></div>";
sys_globalVar["sys_topLogo_sc"] = "<div id='sys_topLogoDiv' style='display:inline;'><a href='/web/sc/index.html' class='logo-iec'><img src='/web/images/common/img-logo-iec.jpg' alt='' /></a></div>";

sys_globalVar["sys_topIndexLogo_en"] = "<p>The Investor Education Centre is supported by the financial regulators</p><img src='/web/images/common/img-supported-by.jpg' alt=''>";
sys_globalVar["sys_topIndexLogo_tc"] = "<p>&#25237;&#36039;&#32773;&#25945;&#32946;&#20013;&#24515;&#28858;&#37329;&#34701;&#30435;&#31649;&#30070;&#23616;&#25903;&#25345;&#30340;&#27231;&#27083;</p><img src='/web/images/common/img-supported-by.jpg' alt=''>";
sys_globalVar["sys_topIndexLogo_sc"] = "<p>&#25237;&#36039;&#32773;&#25945;&#32946;&#20013;&#24515;&#28858;&#37329;&#34701;&#30435;&#31649;&#30070;&#23616;&#25903;&#25345;&#30340;&#27231;&#27083;</p><img src='/web/images/common/img-supported-by.jpg' alt=''>";

sys_globalVar["sys_topLink_en"] = "<a href='/web/en/about-iec/index.html'>About IEC</a>&nbsp;&nbsp;<a href='/web/common/apps/en/contact_enquiry.html'>Contact Us</a>";
sys_globalVar["sys_topLink_tc"] = "<a href='/web/tc/about-iec/index.html'>\u6295\u8CC7\u8005\u6559\u80B2\u4E2D\u5FC3\u7C21\u4ECB</a>&nbsp;&nbsp;<a href='/web/common/apps/tc/contact_enquiry.html'>\u806F\u7D61\u6211\u5011</a>";
sys_globalVar["sys_topLink_sc"] = "<a href='/web/sc/about-iec/index.html'>\u6295\u8CC7\u8005\u6559\u80B2\u4E2D\u5FC3\u7C21\u4ECB</a>&nbsp;&nbsp;<a href='/web/common/apps/tc/contact_enquiry.html'>\u806F\u7D61\u6211\u5011</a>";

sys_globalVar["sys_topSearch_en"] = "<div class='front'></div><form id='TopSearchForm' name='TopSearchForm' method='get' action='/search'><input id='client' type='hidden' name='client' value='sfc'><input id='output' type='hidden' name='output' value='xml_no_dtd'><input id='proxystylesheet' type='hidden' name='proxystylesheet' value='sfc'><input id='ui_lang' type='hidden' name='ui_lang' value='en'><input id='sort' type='hidden' name='sort' value='date%3AD%3AL%3Ad1'><input id='entsp' type='hidden' name='entsp' value='a__html_first_priority'><input id='oe' type='hidden' name='oe' value='UTF-8'><input id='ie' type='hidden' name='ie' value='utf-8'><input id='ud' type='hidden' name='ud' value='1'><input id='exclude_apps' type='hidden' name='exclude_apps' value='1'><input id='site' type='hidden' name='site' value='default_collection'><input id='q' class='searchField' type='text' name='q' placeholder='Search'></form><a href=\"javascript:document.getElementById(\'TopSearchForm\').submit();\"></a><div class='behind'></div>";
sys_globalVar["sys_topSearch_tc"] = "<div class='front'></div><form id='TopSearchForm' name='TopSearchForm' method='get' action='/search'><input id='client' type='hidden' name='client' value='sfc'><input id='output' type='hidden' name='output' value='xml_no_dtd'><input id='proxystylesheet' type='hidden' name='proxystylesheet' value='sfc'><input id='ui_lang' type='hidden' name='ui_lang' value='tc'><input id='sort' type='hidden' name='sort' value='date%3AD%3AL%3Ad1'><input id='entsp' type='hidden' name='entsp' value='a__html_first_priority'><input id='oe' type='hidden' name='oe' value='UTF-8'><input id='ie' type='hidden' name='ie' value='utf-8'><input id='ud' type='hidden' name='ud' value='1'><input id='exclude_apps' type='hidden' name='exclude_apps' value='1'><input id='site' type='hidden' name='site' value='default_collection'><input id='q' class='searchField' type='text' name='q' placeholder='\u641C\u5C0B'></form><a href=\"javascript:document.getElementById(\'TopSearchForm\').submit();\"></a><div class='behind'></div>";
sys_globalVar["sys_topSearch_sc"] = "<div class='front'></div><form id='TopSearchForm' name='TopSearchForm' method='get' action='/search'><input id='client' type='hidden' name='client' value='sfc'><input id='output' type='hidden' name='output' value='xml_no_dtd'><input id='proxystylesheet' type='hidden' name='proxystylesheet' value='sfc'><input id='ui_lang' type='hidden' name='ui_lang' value='tc'><input id='sort' type='hidden' name='sort' value='date%3AD%3AL%3Ad1'><input id='entsp' type='hidden' name='entsp' value='a__html_first_priority'><input id='oe' type='hidden' name='oe' value='UTF-8'><input id='ie' type='hidden' name='ie' value='utf-8'><input id='ud' type='hidden' name='ud' value='1'><input id='exclude_apps' type='hidden' name='exclude_apps' value='1'><input id='site' type='hidden' name='site' value='default_collection'><input id='q' class='searchField' type='text' name='q' placeholder='\u641C\u5C0B'></form><a href=\"javascript:document.getElementById(\'TopSearchForm\').submit();\"></a><div class='behind'></div>";

sys_globalVar["sys_topLang_en"] = "<a href=\"javascript:sitemap_changeLangFromEn('tc');\">&#32321;</a>&nbsp;&#8231;&nbsp;<a href=\"/web/en/popup-disclaimer.html\" class=\"btn-sc\">&#31777;</a>&nbsp;<span>|</span>&nbsp;<a href=\"javascript:changeFont(-1);\" class=\"font-size small\"><img src=\"/web/images/common/small.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(0);\" class=\"font-size medium\"><img src=\"/web/images/common/medium.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(1);\" class=\"font-size big\"><img src=\"/web/images/common/big.jpg\" alt=\"\"></a>";
sys_globalVar["sys_topLang_tc"] = "<a href=\"javascript:sitemap_changeLangFromTc('en');\">EN</a>&nbsp;&#8231;&nbsp;<a href=\"/web/en/popup-disclaimer.html\" class=\"btn-sc\">&#31777;</a>&nbsp;<span>|</span>&nbsp;<a href=\"javascript:changeFont(-1);\" class=\"font-size small\"><img src=\"/web/images/common/small.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(0);\" class=\"font-size medium\"><img src=\"/web/images/common/medium.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(1);\" class=\"font-size big\"><img src=\"/web/images/common/big.jpg\" alt=\"\"></a>";
sys_globalVar["sys_topLang_sc"] = "<a href=\"javascript:sitemap_changeLangFromSc('en');\">EN</a>&nbsp;&#8231;&nbsp;<a href=\"javascript:sitemap_changeLangFromSc('tc');\">&#32321;</a>&nbsp;<span>|</span>&nbsp;<a href=\"javascript:changeFont(-1);\" class=\"font-size small\"><img src=\"/web/images/common/small.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(0);\" class=\"font-size medium\"><img src=\"/web/images/common/medium.jpg\" alt=\"\"></a>&nbsp;<a href=\"javascript:changeFont(1);\" class=\"font-size big\"><img src=\"/web/images/common/big.jpg\" alt=\"\"></a>";

sys_globalVar["sys_footerTop_en"] = "<ul><li class='enews'><input class='ipt_sub' id='mail' name='mail' type='text' placeholder='Your e-mail address'><br><a href='/web/en/tools-and-resources/e-newsletters/index.html' class='btn'>Latest issue</a><a href='javascript:goToSubscriptionPage(\"en\");' target='_self'  class='btn btn_sub'>Subscribe</a></li><li><a href='/web/en/others/activities-and-events/index.html' class='btn-activities'>Campaigns &<br>Activities</a></li><li><a href='/web/en/tools-and-resources/multimedia/index.html' class='btn-multimedia'>Multimedia</a></li><li><a href='/web/en/tools-and-resources/tools/index.html' class='btn-calculators'>Calculators</a></li><li><a href='/web/en/hot-topics.html' class='btn-hot-topic'>Hot Topics</a></li><li><a href='/web/en/tools-and-resources/cases/index.html' class='btn-cases'>Cases</a></li><li><a href='/web/en/tools-and-resources/publications.html' class='btn-publications'>Publications</a></li><li class='last'><a href='/web/en/tools-and-resources/glossary.html' class='btn-glossary'>Glossary</a></li></ul><div class='clearfix'></div>";
sys_globalVar["sys_footerTop_tc"] = "<ul><li class='enews'><input class='ipt_sub' id='mail' name='mail' type='text' placeholder='\u60A8\u7684\u96FB\u90F5\u5730\u5740'><br><a href='/web/tc/tools-and-resources/e-newsletters/index.html' class='btn'>\u6700\u65B0\u901A\u8A0A</a><a href='javascript:goToSubscriptionPage(\"tc\");' target='_self'  class='btn btn_sub'>\u7ACB\u5373\u767B\u8A18</a></li><li><a href='/web/tc/others/activities-and-events/index.html' class='btn-activities'>\u6D3B\u52D5</a></li><li><a href='/web/tc/tools-and-resources/multimedia/index.html' class='btn-multimedia'>\u591A\u5A92\u9AD4</a></li><li><a href='/web/tc/tools-and-resources/tools/index.html' class='btn-calculators'>\u8A08\u7B97\u6A5F</a></li><li><a href='/web/tc/hot-topics.html' class='btn-hot-topic'>\u71B1\u9580\u5C08\u984C</a></li><li><a href='/web/tc/tools-and-resources/cases/index.html' class='btn-cases'>\u500B\u6848</a></li><li><a href='/web/tc/tools-and-resources/publications.html' class='btn-publications'>\u520A\u7269\u5EAB</a></li><li class='last'><a href='/web/tc/tools-and-resources/glossary.html' class='btn-glossary'>\u8A5E\u5F59</a></li></ul><div class='clearfix'></div>";
sys_globalVar["sys_footerTop_sc"] = "<ul><li class='enews'><input class='ipt_sub' id='mail' name='mail' type='text' placeholder='\u60A8\u7684\u96FB\u90F5\u5730\u5740'><br><a href='/web/sc/tools-and-resources/e-newsletters/index.html' class='btn'>\u6700\u65B0\u901A\u8A0A</a><a href='javascript:goToSubscriptionPage(\"tc\");' target='_self'  class='btn btn_sub'>\u7ACB\u5373\u767B\u8A18</a></li><li><a href='/web/sc/others/activities-and-events/index.html' class='btn-activities'>\u6D3B\u52D5</a></li><li><a href='/web/sc/tools-and-resources/multimedia/index.html' class='btn-multimedia'>\u591A\u5A92\u9AD4</a></li><li><a href='/web/sc/tools-and-resources/tools/index.html' class='btn-calculators'>\u8A08\u7B97\u6A5F</a></li><li><a href='/web/sc/hot-topics.html' class='btn-hot-topic'>\u71B1\u9580\u5C08\u984C</a></li><li><a href='/web/sc/tools-and-resources/cases/index.html' class='btn-cases'>\u500B\u6848</a></li><li><a href='/web/sc/tools-and-resources/publications.html' class='btn-publications'>\u520A\u7269\u5EAB</a></li><li class='last'><a href='/web/sc/tools-and-resources/glossary.html' class='btn-glossary'>\u8A5E\u5F59</a></li></ul><div class='clearfix'></div>";

sys_globalVar["sys_footerBottom_en"] = "<div class='wrapper'><a href='/web/en/others/sitemap.html'>Site Map</a><a href='/web/en/others/liability-statement.html'>Liability Statement</a><a href='/web/en/others/privacy-policy.html'>Privacy Policy</a><a href='/web/en/others/hyperlink-policy.html'>Hyperlink Policy</a><p class='floatR'>Copyright \u00A92015 Investor Education Centre. All right reserved.</p><br/></div>";
sys_globalVar["sys_footerBottom_tc"] = "<div class='wrapper'><a href='/web/tc/others/sitemap.html'>\u7DB2\u7AD9\u6307\u5357</a><a href='/web/tc/others/liability-statement.html'>\u514D\u8CAC\u8072\u660E</a><a href='/web/tc/others/privacy-policy.html'>\u79C1\u96B1\u653F\u7B56\u8072\u660E</a><a href='/web/tc/others/hyperlink-policy.html'>\u8D85\u9023\u7D50\u653F\u7B56</a><p class='floatR'>\u00A92015 \u6295\u8CC7\u8005\u6559\u80B2\u4E2D\u5FC3 \u7248\u6B0A\u6240\u6709\u3002</p><br/></div>";
sys_globalVar["sys_footerBottom_sc"] = "<div class='wrapper'><a href='/web/sc/others/sitemap.html'>\u7DB2\u7AD9\u6307\u5357</a><a href='/web/sc/others/liability-statement.html'>\u514D\u8CAC\u8072\u660E</a><a href='/web/sc/others/privacy-policy.html'>\u79C1\u96B1\u653F\u7B56\u8072\u660E</a><a href='/web/sc/others/hyperlink-policy.html'>\u8D85\u9023\u7D50\u653F\u7B56</a><p class='floatR'>\u00A92015 \u6295\u8CC7\u8005\u6559\u80B2\u4E2D\u5FC3 \u7248\u6B0A\u6240\u6709\u3002</p><br/></div>";

sys_globalVar["sys_socialMedia_en"] = "<div class='social-media-wrapper'><div class='innerwrapper'><a onclick='popupYoutube(0)' href='javascript:;' class='btn-youtube'> </a><a href='javascript:;' onclick='fb_share(0)' class='btn-facebook-share'></a><!--<a href='javascript:mailTo(0);' class='btn-email'> </a>--><a href='javascript:;' onclick='printPage(0)' class='btn-print'> </a><a href='javascript:;' class='btn-myfav'> </a><div class='myfav-wrapper'><h2>My Favourite Pages</h2><div id='topsbfavourite' class='my-fav-inner-wrapper'><ul></ul><a href='javascript:;' class='btn-add-this-pages' onclick='addFav()'>Add this page</a></div><img src='/web/images/common/bg-myfav-inner-b.gif' alt='' width='133' height='5'></div><a href='javascript:;' class='btn-top'></a></div></div>";
sys_globalVar["sys_socialMedia_tc"] = "<div class='social-media-wrapper'><div class='innerwrapper'><a onclick='popupYoutube(1)' href='javascript:;' class='btn-youtube'> </a><a href='javascript:;' onclick='fb_share(1)' class='btn-facebook-share'></a><!--<a href='javascript:mailTo(1);' class='btn-email'> </a>--><a href='javascript:;' onclick='printPage(1)' class='btn-print'> </a><a href='javascript:;' class='btn-myfav'> </a><div class='myfav-wrapper'><h2>\u6211\u7684\u6700\u611B</h2><div id='topsbfavourite' class='my-fav-inner-wrapper'><ul></ul><a href='javascript:;' class='btn-add-this-pages' onclick='addFav()'>\u6DFB\u52A0\u6B64\u9801</a></div><img src='/web/images/common/bg-myfav-inner-b.gif' alt='' width='133' height='5'></div><a href='javascript:;' class='btn-top'></a></div></div>";
sys_globalVar["sys_socialMedia_sc"] = "<div class='social-media-wrapper'><div class='innerwrapper'><a onclick='popupYoutube(2)' href='javascript:;' class='btn-youtube'> </a><a href='javascript:;' onclick='fb_share(2)' class='btn-facebook-share'></a><!--<a href='javascript:mailTo(2);' class='btn-email'> </a>--><a href='javascript:;' onclick='printPage(2)' class='btn-print'> </a><a href='javascript:;' class='btn-myfav'> </a><div class='myfav-wrapper'><h2>\u6211\u7684\u6700\u611B</h2><div id='topsbfavourite' class='my-fav-inner-wrapper'><ul></ul><a href='javascript:;' class='btn-add-this-pages' onclick='addFav()'>\u6DFB\u52A0\u6B64\u9801</a></div><img src='/web/images/common/bg-myfav-inner-b.gif' alt='' width='133' height='5'></div><a href='javascript:;' class='btn-top'></a></div></div>";

function iecGlobalUpdate(langId)
{
	var sCurURL = window.location.href;
	//alert("[iecGlobalUpdate] langId = " + langId);
	var topLogoDivObj = document.getElementById("sys_topLogoDiv");
	if(topLogoDivObj){topLogoDivObj.innerHTML = sys_globalVar["sys_topLogo_" + langId];}
	
	var topIndexLogoDivObj = document.getElementById("sys_topIndexLogoDiv");
	if(topIndexLogoDivObj && (sCurURL.indexOf("/web/en/index.html") > -1 || sCurURL.indexOf("/web/tc/index.html") > -1 || sCurURL.indexOf("/web/sc/index.html") > -1)){topIndexLogoDivObj.innerHTML = sys_globalVar["sys_topIndexLogo_" + langId];}
	
	var topLinkDivObj = document.getElementById("sys_topLinkDiv");
	if(topLinkDivObj){topLinkDivObj.innerHTML = sys_globalVar["sys_topLink_" + langId];}
	
	var topSearchDivObj = document.getElementById("sys_topSearchDiv");
	if(topSearchDivObj){topSearchDivObj.innerHTML = sys_globalVar["sys_topSearch_" + langId];}
	
	var topLangDivObj = document.getElementById("sys_topLangDiv");
	if(topLangDivObj){topLangDivObj.innerHTML = sys_globalVar["sys_topLang_" + langId];}
	
	var footerTopDivObj = document.getElementById("sys_footerTopDiv");
	if(footerTopDivObj){footerTopDivObj.innerHTML = sys_globalVar["sys_footerTop_" + langId];}
	
	var footerBottomDivObj = document.getElementById("sys_footerBottomDiv");
	if(footerBottomDivObj){footerBottomDivObj.innerHTML = sys_globalVar["sys_footerBottom_" + langId];}
	
	var socialMediaDivObj = document.getElementById("sys_socialMediaDiv");
	if(socialMediaDivObj){socialMediaDivObj.innerHTML = sys_globalVar["sys_socialMedia_" + langId];}
	//alert("[iecGlobalUpdate] langId = " + langId + ", footerBottomDivObj = " + footerBottomDivObj);
}

function goToSubscriptionPage(_lang) {
	if(document.getElementById("mail") !== null && document.getElementById("mail") !== '') {
		window.location.href = '/subscription/subscription.jsp?lang=' + _lang + '&mail=' + document.getElementById("mail").value;
	}else {
		window.location.href = '/subscription/subscription.jsp?lang=' + _lang;	
	}
}